<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <RootNamespace>GB_CadAndSWPlus_V.SolidWorksAddIn</RootNamespace>
    <AssemblyName>GB_CadAndSWPlus_V_SolidWorksAddIn</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RegisterForComInterop>false</RegisterForComInterop>
    <ComVisible>true</ComVisible>
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SolidWorks.Interop.sldworks">
      <HintPath>D:\Program Files\SolidWorkS2022\SOLIDWORKS\api\redist\SolidWorks.Interop.sldworks.dll</HintPath>
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <Private>false</Private>
    </Reference>
    <Reference Include="SolidWorks.Interop.swconst">
      <HintPath>D:\Program Files\SolidWorkS2022\SOLIDWORKS\api\redist\SolidWorks.Interop.swconst.dll</HintPath>
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <Private>false</Private>
    </Reference>
    <Reference Include="SolidWorks.Interop.swpublished">
      <HintPath>D:\Program Files\SolidWorkS2022\SOLIDWORKS\api\redist\SolidWorks.Interop.swpublished.dll</HintPath>
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
