-- 统一登录服务端会话表（达梦）
-- 执行前请确认 CAD_SW_LIBRARY Schema 已存在，并先备份数据库。
-- token 只保存 SHA-256 摘要，客户端持有的原始 token 不写入数据库。

/*


*/
CREATE TABLE CAD_SW_LIBRARY.AUTH_SESSIONS (
	ID BIGINT NOT NULL,
	USER_ID INT NOT NULL,
	TOKEN_HASH VARCHAR(128) NOT NULL,
	CLIENT_PLATFORM VARCHAR(32) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	EXPIRES_AT TIMESTAMP NOT NULL,
	REVOKED_AT TIMESTAMP,
	LAST_SEEN_AT TIMESTAMP,
	CONSTRAINT PK_AUTH_SESSIONS PRIMARY KEY (ID),
	CONSTRAINT UK_AUTH_SESSIONS_TOKEN_HASH UNIQUE (TOKEN_HASH)
);

CREATE INDEX CAD_SW_LIBRARY.IX_AUTH_SESSIONS_USER
	ON CAD_SW_LIBRARY.AUTH_SESSIONS (USER_ID, REVOKED_AT, EXPIRES_AT);

CREATE INDEX CAD_SW_LIBRARY.IX_AUTH_SESSIONS_EXPIRES
	ON CAD_SW_LIBRARY.AUTH_SESSIONS (EXPIRES_AT);

-- 若数据库不支持自动序列，请将此序列用于 ID 生成。
CREATE SEQUENCE CAD_SW_LIBRARY.AUTH_SESSIONS_SEQ
	START WITH 1
	INCREMENT BY 1;
