-- CAD PID 与 SolidWorks 实例关联表（达梦）
-- 默认 Schema 为 CAD_SW_LIBRARY；如实际配置不同，请替换下方 Schema。
CREATE TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES (
	SW_INSTANCE_ID VARCHAR(128) NOT NULL,
	PID_INSTANCE_ID VARCHAR(128) NOT NULL,
	LIBRARY_ITEM_ID INT,
	DOCUMENT_PATH VARCHAR(1000),
	DOCUMENT_NAME VARCHAR(255),
	ASSEMBLY_NAME VARCHAR(255),
	COMPONENT_NAME VARCHAR(255),
	CONFIGURATION_NAME VARCHAR(255),
	TRANSFORM_JSON TEXT,
	CUSTOM_PROPERTIES_JSON TEXT,
	VERSION INT DEFAULT 1 NOT NULL,
	SYNC_STATUS VARCHAR(32) DEFAULT 'SYNCED' NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_SW_MODEL_INSTANCES PRIMARY KEY (SW_INSTANCE_ID)
);
CREATE INDEX CAD_SW_LIBRARY.IX_SW_MODEL_INSTANCES_PID ON CAD_SW_LIBRARY.SW_MODEL_INSTANCES (PID_INSTANCE_ID);
CREATE INDEX CAD_SW_LIBRARY.IX_SW_MODEL_INSTANCES_LIBRARY ON CAD_SW_LIBRARY.SW_MODEL_INSTANCES (LIBRARY_ITEM_ID);
