-- 统一构件图元库一期试点数据：达梦 DM
-- 依赖：element_library_schema_dm.sql 已执行。
-- 说明：仅创建三个构件业务身份，不绑定文件、不修改旧 CAD/SW 资源。
-- 执行前请根据实际分类树，将 CATEGORY_ID 替换为对应分类 ID；为空时允许后续管理员补充。

DECLARE
	V_COUNT INT;
	V_NOW TIMESTAMP := CURRENT_TIMESTAMP;
BEGIN
	SELECT COUNT(1) INTO V_COUNT FROM CAD_SW_LIBRARY.ELEMENT_DEFINITIONS WHERE ELEMENT_CODE = 'VALVE-BFV-FLG-001';
	IF V_COUNT = 0 THEN
		INSERT INTO CAD_SW_LIBRARY.ELEMENT_DEFINITIONS
			(ID, ELEMENT_CODE, NAME, DISPLAY_NAME, CATEGORY_ID, ELEMENT_TYPE, DISCIPLINE, DESCRIPTION, STATUS, CURRENT_VERSION, CREATED_AT, UPDATED_AT)
		VALUES
			(1000001, 'VALVE-BFV-FLG-001', '蝶阀（法兰）', '蝶阀（法兰）', NULL, 'Valve', 'Process', '一期试点构件：法兰连接蝶阀。', 'DRAFT', 1, V_NOW, V_NOW);
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM CAD_SW_LIBRARY.ELEMENT_DEFINITIONS WHERE ELEMENT_CODE = 'FLANGE-GENERAL-001';
	IF V_COUNT = 0 THEN
		INSERT INTO CAD_SW_LIBRARY.ELEMENT_DEFINITIONS
			(ID, ELEMENT_CODE, NAME, DISPLAY_NAME, CATEGORY_ID, ELEMENT_TYPE, DISCIPLINE, DESCRIPTION, STATUS, CURRENT_VERSION, CREATED_AT, UPDATED_AT)
		VALUES
			(1000002, 'FLANGE-GENERAL-001', '法兰', '法兰', NULL, 'Flange', 'Process', '一期试点构件：通用法兰。', 'DRAFT', 1, V_NOW, V_NOW);
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM CAD_SW_LIBRARY.ELEMENT_DEFINITIONS WHERE ELEMENT_CODE = 'BLIND-PIPE-END-001';
	IF V_COUNT = 0 THEN
		INSERT INTO CAD_SW_LIBRARY.ELEMENT_DEFINITIONS
			(ID, ELEMENT_CODE, NAME, DISPLAY_NAME, CATEGORY_ID, ELEMENT_TYPE, DISCIPLINE, DESCRIPTION, STATUS, CURRENT_VERSION, CREATED_AT, UPDATED_AT)
		VALUES
			(1000003, 'BLIND-PIPE-END-001', '管端盲板', '管端盲板', NULL, 'BlindPlate', 'Process', '一期试点构件：管端盲板。', 'DRAFT', 1, V_NOW, V_NOW);
	END IF;
END;
/

SELECT ID, ELEMENT_CODE, NAME, CATEGORY_ID, STATUS, CURRENT_VERSION
FROM CAD_SW_LIBRARY.ELEMENT_DEFINITIONS
WHERE ELEMENT_CODE IN ('VALVE-BFV-FLG-001', 'FLANGE-GENERAL-001', 'BLIND-PIPE-END-001')
ORDER BY ID;
