-- 统一构件属性与 SolidWorks 元数据一期脚本：达梦 DM
-- 依赖：element_library_schema_dm.sql 已执行。
-- 兼容原则：不修改 CAD_BLOCK_ATTRIBUTES_JSON；现有 CAD 属性继续保留。

DECLARE
	V_COUNT INT;
BEGIN
	SELECT COUNT(1) INTO V_COUNT FROM ALL_TABLES
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'ELEMENT_PROPERTY_DEFINITIONS';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE '
CREATE TABLE CAD_SW_LIBRARY.ELEMENT_PROPERTY_DEFINITIONS (
	ID BIGINT NOT NULL,
	ELEMENT_DEFINITION_ID BIGINT NOT NULL,
	PROPERTY_CODE VARCHAR(128) NOT NULL,
	PROPERTY_NAME VARCHAR(255) NOT NULL,
	DATA_TYPE VARCHAR(32) DEFAULT ''TEXT'' NOT NULL,
	UNIT VARCHAR(64),
	IS_REQUIRED INT DEFAULT 0 NOT NULL,
	SORT_ORDER INT DEFAULT 0 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_ELEMENT_PROPERTY_DEFINITIONS PRIMARY KEY (ID),
	CONSTRAINT UK_ELEMENT_PROPERTY_CODE UNIQUE (ELEMENT_DEFINITION_ID, PROPERTY_CODE),
	CONSTRAINT FK_ELEMENT_PROPERTY_ELEMENT FOREIGN KEY (ELEMENT_DEFINITION_ID)
		REFERENCES CAD_SW_LIBRARY.ELEMENT_DEFINITIONS(ID)
)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TABLES
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'ELEMENT_PROPERTY_VALUES';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE '
CREATE TABLE CAD_SW_LIBRARY.ELEMENT_PROPERTY_VALUES (
	ID BIGINT NOT NULL,
	ELEMENT_DEFINITION_ID BIGINT NOT NULL,
	PROPERTY_DEFINITION_ID BIGINT NOT NULL,
	VALUE_TEXT VARCHAR(2000),
	VALUE_NUMBER DECIMAL(20,6),
	VALUE_BOOL INT,
	SOURCE VARCHAR(32) DEFAULT ''MANUAL'' NOT NULL,
	VERSION INT DEFAULT 1 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_ELEMENT_PROPERTY_VALUES PRIMARY KEY (ID),
	CONSTRAINT UK_ELEMENT_PROPERTY_VALUE UNIQUE (ELEMENT_DEFINITION_ID, PROPERTY_DEFINITION_ID),
	CONSTRAINT FK_ELEMENT_PROPERTY_VALUE_ELEMENT FOREIGN KEY (ELEMENT_DEFINITION_ID)
		REFERENCES CAD_SW_LIBRARY.ELEMENT_DEFINITIONS(ID),
	CONSTRAINT FK_ELEMENT_PROPERTY_VALUE_DEF FOREIGN KEY (PROPERTY_DEFINITION_ID)
		REFERENCES CAD_SW_LIBRARY.ELEMENT_PROPERTY_DEFINITIONS(ID)
)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TABLES
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_ELEMENT_DEFINITIONS';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE '
CREATE TABLE CAD_SW_LIBRARY.SW_ELEMENT_DEFINITIONS (
	ELEMENT_DEFINITION_ID BIGINT NOT NULL,
	MODEL_TYPE VARCHAR(32),
	DEFAULT_CONFIGURATION VARCHAR(255),
	COORDINATE_SYSTEM_NAME VARCHAR(255),
	MATE_RULE_JSON TEXT,
	PORT_COUNT INT DEFAULT 0 NOT NULL,
	MODEL_STATUS VARCHAR(32) DEFAULT ''DRAFT'' NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_SW_ELEMENT_DEFINITIONS PRIMARY KEY (ELEMENT_DEFINITION_ID),
	CONSTRAINT FK_SW_ELEMENT_DEFINITION_ELEMENT FOREIGN KEY (ELEMENT_DEFINITION_ID)
		REFERENCES CAD_SW_LIBRARY.ELEMENT_DEFINITIONS(ID)
)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TABLES
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_CONNECTION_POINTS';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE '
CREATE TABLE CAD_SW_LIBRARY.SW_CONNECTION_POINTS (
	ID BIGINT NOT NULL,
	ELEMENT_DEFINITION_ID BIGINT NOT NULL,
	POINT_CODE VARCHAR(128) NOT NULL,
	POINT_TYPE VARCHAR(64),
	POSITION_JSON VARCHAR(2000),
	DIRECTION_JSON VARCHAR(2000),
	DIAMETER DECIMAL(20,6),
	UNIT VARCHAR(32),
	SORT_ORDER INT DEFAULT 0 NOT NULL,
	CONSTRAINT PK_SW_CONNECTION_POINTS PRIMARY KEY (ID),
	CONSTRAINT UK_SW_CONNECTION_POINT_CODE UNIQUE (ELEMENT_DEFINITION_ID, POINT_CODE),
	CONSTRAINT FK_SW_CONNECTION_POINT_ELEMENT FOREIGN KEY (ELEMENT_DEFINITION_ID)
		REFERENCES CAD_SW_LIBRARY.ELEMENT_DEFINITIONS(ID)
)';
	END IF;
END;
/

CREATE INDEX CAD_SW_LIBRARY.IX_ELEMENT_PROPERTY_DEF_ELEMENT
	ON CAD_SW_LIBRARY.ELEMENT_PROPERTY_DEFINITIONS (ELEMENT_DEFINITION_ID, SORT_ORDER);
CREATE INDEX CAD_SW_LIBRARY.IX_SW_CONNECTION_POINTS_ELEMENT
	ON CAD_SW_LIBRARY.SW_CONNECTION_POINTS (ELEMENT_DEFINITION_ID, SORT_ORDER);
