-- CAD/SolidWorks 统一构件图元库一期数据库脚本：达梦 DM
-- 作用：新增统一构件定义和平台资源关联表。
-- 兼容原则：不修改、不删除 CAD_FILE_STORAGE、CAD_BLOCK_ATTRIBUTES_JSON、SW_MODEL_INSTANCES 及离线 Resources。
-- 执行前请备份数据库，并确认 Schema 为 CAD_SW_LIBRARY。
-- 本脚本不自动迁移旧数据；旧 CAD 图元将在后续绑定 API 中逐步关联。

DECLARE
	V_COUNT INT;
BEGIN
	SELECT COUNT(1) INTO V_COUNT
	FROM ALL_TABLES
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'ELEMENT_DEFINITIONS';

	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE '
CREATE TABLE CAD_SW_LIBRARY.ELEMENT_DEFINITIONS (
	ID BIGINT NOT NULL,
	ELEMENT_CODE VARCHAR(128) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	DISPLAY_NAME VARCHAR(255),
	CATEGORY_ID INT,
	ELEMENT_TYPE VARCHAR(64),
	DISCIPLINE VARCHAR(64),
	STANDARD_NO VARCHAR(128),
	DESCRIPTION VARCHAR(1000),
	STATUS VARCHAR(32) DEFAULT ''DRAFT'' NOT NULL,
	CURRENT_VERSION INT DEFAULT 1 NOT NULL,
	CREATED_BY VARCHAR(128),
	UPDATED_BY VARCHAR(128),
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_ELEMENT_DEFINITIONS PRIMARY KEY (ID),
	CONSTRAINT UK_ELEMENT_DEFINITIONS_CODE UNIQUE (ELEMENT_CODE)
)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM ALL_TABLES
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'ELEMENT_RESOURCES';

	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE '
CREATE TABLE CAD_SW_LIBRARY.ELEMENT_RESOURCES (
	ID BIGINT NOT NULL,
	ELEMENT_DEFINITION_ID BIGINT NOT NULL,
	PLATFORM VARCHAR(32) NOT NULL,
	RESOURCE_TYPE VARCHAR(32) NOT NULL,
	FILE_STORAGE_ID INT,
	RESOURCE_NAME VARCHAR(255),
	RESOURCE_PATH VARCHAR(1000),
	FILE_HASH VARCHAR(128),
	VERSION INT DEFAULT 1 NOT NULL,
	CONFIGURATION_NAME VARCHAR(255),
	STATUS VARCHAR(32) DEFAULT ''DRAFT'' NOT NULL,
	IS_DEFAULT INT DEFAULT 0 NOT NULL,
	CREATED_BY VARCHAR(128),
	UPDATED_BY VARCHAR(128),
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_ELEMENT_RESOURCES PRIMARY KEY (ID),
	CONSTRAINT FK_ELEMENT_RESOURCES_DEFINITION FOREIGN KEY (ELEMENT_DEFINITION_ID)
		REFERENCES CAD_SW_LIBRARY.ELEMENT_DEFINITIONS(ID)
)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM ALL_INDEXES
	WHERE OWNER = 'CAD_SW_LIBRARY' AND INDEX_NAME = 'IX_ELEMENT_DEFINITIONS_CATEGORY';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX CAD_SW_LIBRARY.IX_ELEMENT_DEFINITIONS_CATEGORY ON CAD_SW_LIBRARY.ELEMENT_DEFINITIONS (CATEGORY_ID, STATUS)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM ALL_INDEXES
	WHERE OWNER = 'CAD_SW_LIBRARY' AND INDEX_NAME = 'IX_ELEMENT_RESOURCES_ELEMENT';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX CAD_SW_LIBRARY.IX_ELEMENT_RESOURCES_ELEMENT ON CAD_SW_LIBRARY.ELEMENT_RESOURCES (ELEMENT_DEFINITION_ID, PLATFORM, STATUS)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM ALL_INDEXES
	WHERE OWNER = 'CAD_SW_LIBRARY' AND INDEX_NAME = 'IX_ELEMENT_RESOURCES_FILE';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX CAD_SW_LIBRARY.IX_ELEMENT_RESOURCES_FILE ON CAD_SW_LIBRARY.ELEMENT_RESOURCES (FILE_STORAGE_ID)';
	END IF;
END;
/

-- 执行后核验表、约束和索引是否存在。
SELECT OWNER, TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = 'CAD_SW_LIBRARY'
  AND TABLE_NAME IN ('ELEMENT_DEFINITIONS', 'ELEMENT_RESOURCES')
ORDER BY TABLE_NAME;

SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS
FROM ALL_CONSTRAINTS
WHERE OWNER = 'CAD_SW_LIBRARY'
  AND TABLE_NAME IN ('ELEMENT_DEFINITIONS', 'ELEMENT_RESOURCES')
ORDER BY TABLE_NAME, CONSTRAINT_NAME;
