-- 统一构件资源附件一期脚本：达梦 DM
-- 作用：为 ELEMENT_RESOURCES 增加预览图片和轻量三维预览附件记录。
-- 兼容原则：不修改旧 CAD_FILE_STORAGE、SW_GRAPHICS 和现有 ELEMENT_RESOURCES 数据。
-- 执行前请确认 ELEMENT_RESOURCES 已创建，并已完成数据库备份。

DECLARE
	V_COUNT INT;
BEGIN
	SELECT COUNT(1) INTO V_COUNT
	FROM ALL_TABLES
	WHERE OWNER = 'CAD_SW_LIBRARY'
	  AND TABLE_NAME = 'ELEMENT_RESOURCE_ATTACHMENTS';

	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE '
CREATE TABLE CAD_SW_LIBRARY.ELEMENT_RESOURCE_ATTACHMENTS (
	ID BIGINT NOT NULL,
	RESOURCE_ID BIGINT NOT NULL,
	ATTACHMENT_TYPE VARCHAR(32) NOT NULL,
	ORIGINAL_FILE_NAME VARCHAR(255) NOT NULL,
	STORED_FILE_NAME VARCHAR(255),
	MIME_TYPE VARCHAR(128),
	FILE_PATH VARCHAR(1000) NOT NULL,
	FILE_HASH VARCHAR(128),
	FILE_SIZE BIGINT,
	VERSION INT DEFAULT 1 NOT NULL,
	STATUS VARCHAR(32) DEFAULT ''DRAFT'' NOT NULL,
	CREATED_BY VARCHAR(128),
	UPDATED_BY VARCHAR(128),
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_ELEMENT_RESOURCE_ATTACHMENTS PRIMARY KEY (ID),
	CONSTRAINT FK_ELEMENT_RESOURCE_ATTACHMENTS_RESOURCE FOREIGN KEY (RESOURCE_ID)
		REFERENCES CAD_SW_LIBRARY.ELEMENT_RESOURCES(ID)
)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT
	FROM ALL_INDEXES
	WHERE OWNER = 'CAD_SW_LIBRARY'
	  AND INDEX_NAME = 'IX_ELEMENT_RESOURCE_ATTACHMENTS_RESOURCE';

	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE '
CREATE INDEX CAD_SW_LIBRARY.IX_ELEMENT_RESOURCE_ATTACHMENTS_RESOURCE
ON CAD_SW_LIBRARY.ELEMENT_RESOURCE_ATTACHMENTS (RESOURCE_ID, ATTACHMENT_TYPE, STATUS)';
	END IF;
END;
/

SELECT OWNER, TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = 'CAD_SW_LIBRARY'
  AND TABLE_NAME = 'ELEMENT_RESOURCE_ATTACHMENTS';

SELECT OWNER, INDEX_NAME, TABLE_NAME, STATUS
FROM ALL_INDEXES
WHERE OWNER = 'CAD_SW_LIBRARY'
  AND INDEX_NAME = 'IX_ELEMENT_RESOURCE_ATTACHMENTS_RESOURCE';
