-- CAD/SolidWorks 统一构件图元库一期回滚脚本：达梦 DM
-- 高风险操作：仅允许在确认需要撤销本次新增结构时执行。
-- 本脚本只删除本次新增表，不删除 CAD_FILE_STORAGE、CAD_BLOCK_ATTRIBUTES_JSON、SW_MODEL_INSTANCES。

DECLARE
BEGIN
	FOR R IN (
		SELECT TABLE_NAME
		FROM ALL_TABLES
		WHERE OWNER = 'CAD_SW_LIBRARY'
		  AND TABLE_NAME IN (
			  'SW_CONNECTION_POINTS',
			  'SW_ELEMENT_DEFINITIONS',
			  'ELEMENT_PROPERTY_VALUES',
			  'ELEMENT_PROPERTY_DEFINITIONS',
			  'ELEMENT_RESOURCES',
			  'ELEMENT_DEFINITIONS'
		  )
		ORDER BY CASE TABLE_NAME
			WHEN 'SW_CONNECTION_POINTS' THEN 1
			WHEN 'SW_ELEMENT_DEFINITIONS' THEN 2
			WHEN 'ELEMENT_PROPERTY_VALUES' THEN 3
			WHEN 'ELEMENT_PROPERTY_DEFINITIONS' THEN 4
			WHEN 'ELEMENT_RESOURCES' THEN 5
			WHEN 'ELEMENT_DEFINITIONS' THEN 6
			ELSE 99
		END
	) LOOP
		EXECUTE IMMEDIATE 'DROP TABLE CAD_SW_LIBRARY.' || R.TABLE_NAME || ' CASCADE CONSTRAINTS';
	END LOOP;
END;
/

-- 注意：本脚本不回滚 SW_MODEL_INSTANCES 上的新增可空字段。
-- 如确需回滚实例字段，必须先确认没有新 API 或数据依赖，再人工执行 ALTER TABLE DROP COLUMN。
