-- SolidWorks 一期数据库增量升级脚本：达梦版本
-- 适用：已经存在 CAD_SW_LIBRARY 旧数据库的环境。
-- 作用：新增 CAD PID 与 SolidWorks 实例关联表，不删除、不修改既有 CAD、用户、部门、分类和规范数据。
-- 执行前：请先备份数据库，并确认当前执行账号具备 CREATE TABLE、CREATE INDEX 权限。
-- 默认 Schema：CAD_SW_LIBRARY；如实际配置不同，请替换脚本中的 CAD_SW_LIBRARY。
/*
-- ============================================================
-- 1. 创建 SolidWorks 实例关联表（不存在时创建）
-- ============================================================
DECLARE
	V_COUNT INT;
BEGIN
	SELECT COUNT(1) INTO V_COUNT
	FROM ALL_TABLES
	WHERE OWNER = 'CAD_SW_LIBRARY'
	  AND TABLE_NAME = 'SW_MODEL_INSTANCES';

	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE '
CREATE TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES (
	SW_INSTANCE_ID VARCHAR(128) NOT NULL,
	PID_INSTANCE_ID VARCHAR(128) NOT NULL,
	LIBRARY_ITEM_ID INT,
	DOCUMENT_PATH VARCHAR(1000),
	DOCUMENT_NAME VARCHAR(255),
	ASSEMBLY_NAME VARCHAR(255),
	COMPONENT_NAME VARCHAR(255),
	CONFIGURATION_NAME VARCHAR(255),
	TRANSFORM_JSON TEXT,
	CUSTOM_PROPERTIES_JSON TEXT,
	VERSION INT DEFAULT 1 NOT NULL,
	SYNC_STATUS VARCHAR(32) DEFAULT ''SYNCED'' NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT PK_SW_MODEL_INSTANCES PRIMARY KEY (SW_INSTANCE_ID)
)';
	END IF;
END;
/

-- ============================================================
-- 2. 为旧版本已存在的实例表补齐必要列
-- ============================================================
DECLARE
	V_COUNT INT;
BEGIN
	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'PID_INSTANCE_ID';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD PID_INSTANCE_ID VARCHAR(128)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'LIBRARY_ITEM_ID';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD LIBRARY_ITEM_ID INT';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'DOCUMENT_PATH';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD DOCUMENT_PATH VARCHAR(1000)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'DOCUMENT_NAME';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD DOCUMENT_NAME VARCHAR(255)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'ASSEMBLY_NAME';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD ASSEMBLY_NAME VARCHAR(255)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'COMPONENT_NAME';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD COMPONENT_NAME VARCHAR(255)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'CONFIGURATION_NAME';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD CONFIGURATION_NAME VARCHAR(255)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'TRANSFORM_JSON';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD TRANSFORM_JSON TEXT';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'CUSTOM_PROPERTIES_JSON';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD CUSTOM_PROPERTIES_JSON TEXT';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'VERSION';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD VERSION INT DEFAULT 1 NOT NULL';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'SYNC_STATUS';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD SYNC_STATUS VARCHAR(32) DEFAULT ''SYNCED'' NOT NULL';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'CREATED_AT';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD CREATED_AT TIMESTAMP';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'UPDATED_AT';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD UPDATED_AT TIMESTAMP';
	END IF;
END;
/

-- ============================================================
-- 3. 创建查询索引（不存在时创建）
-- ============================================================
DECLARE
	V_COUNT INT;
BEGIN
	SELECT COUNT(1) INTO V_COUNT FROM ALL_INDEXES
	WHERE OWNER = 'CAD_SW_LIBRARY' AND INDEX_NAME = 'IX_SW_MODEL_INSTANCES_PID';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX CAD_SW_LIBRARY.IX_SW_MODEL_INSTANCES_PID ON CAD_SW_LIBRARY.SW_MODEL_INSTANCES (PID_INSTANCE_ID)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_INDEXES
	WHERE OWNER = 'CAD_SW_LIBRARY' AND INDEX_NAME = 'IX_SW_MODEL_INSTANCES_LIBRARY';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX CAD_SW_LIBRARY.IX_SW_MODEL_INSTANCES_LIBRARY ON CAD_SW_LIBRARY.SW_MODEL_INSTANCES (LIBRARY_ITEM_ID)';
	END IF;
END;
/

-- ============================================================
-- 4. 升级结果检查
-- ============================================================
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'CAD_SW_LIBRARY'
  AND TABLE_NAME = 'SW_MODEL_INSTANCES'
ORDER BY COLUMN_ID;

SELECT OWNER, INDEX_NAME, TABLE_NAME
FROM ALL_INDEXES
WHERE OWNER = 'CAD_SW_LIBRARY'
  AND INDEX_NAME IN ('IX_SW_MODEL_INSTANCES_PID', 'IX_SW_MODEL_INSTANCES_LIBRARY');
  */