-- CAD PID 与 SolidWorks 构件实例关联升级脚本：达梦 DM
-- 作用：为现有 SW_MODEL_INSTANCES 增加统一构件定义和项目标识字段。
-- 兼容原则：不删除、不重命名 LIBRARY_ITEM_ID；旧客户端仍可继续读写原字段。
-- 执行前请备份数据库，并确认 Schema 为 CAD_SW_LIBRARY。

DECLARE
	V_COUNT INT;
BEGIN
	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'ELEMENT_DEFINITION_ID';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD ELEMENT_DEFINITION_ID BIGINT';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'PROJECT_CODE';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD PROJECT_CODE VARCHAR(128)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'RESOURCE_ID';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD RESOURCE_ID BIGINT';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_TAB_COLUMNS
	WHERE OWNER = 'CAD_SW_LIBRARY' AND TABLE_NAME = 'SW_MODEL_INSTANCES' AND COLUMN_NAME = 'SELECTED_CONFIGURATION';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE CAD_SW_LIBRARY.SW_MODEL_INSTANCES ADD SELECTED_CONFIGURATION VARCHAR(255)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_INDEXES
	WHERE OWNER = 'CAD_SW_LIBRARY' AND INDEX_NAME = 'IX_SW_MODEL_INSTANCES_ELEMENT';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX CAD_SW_LIBRARY.IX_SW_MODEL_INSTANCES_ELEMENT ON CAD_SW_LIBRARY.SW_MODEL_INSTANCES (ELEMENT_DEFINITION_ID, PROJECT_CODE)';
	END IF;

	SELECT COUNT(1) INTO V_COUNT FROM ALL_INDEXES
	WHERE OWNER = 'CAD_SW_LIBRARY' AND INDEX_NAME = 'IX_SW_MODEL_INSTANCES_RESOURCE';
	IF V_COUNT = 0 THEN
		EXECUTE IMMEDIATE 'CREATE INDEX CAD_SW_LIBRARY.IX_SW_MODEL_INSTANCES_RESOURCE ON CAD_SW_LIBRARY.SW_MODEL_INSTANCES (RESOURCE_ID)';
	END IF;
END;
/

SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'CAD_SW_LIBRARY'
  AND TABLE_NAME = 'SW_MODEL_INSTANCES'
  AND COLUMN_NAME IN ('LIBRARY_ITEM_ID', 'ELEMENT_DEFINITION_ID', 'PROJECT_CODE', 'RESOURCE_ID', 'SELECTED_CONFIGURATION')
ORDER BY COLUMN_ID;
